package com.ycmm.model;

import java.io.Serializable;

public class BaseBizEmployee implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.eName
     *
     * @mbg.generated
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.no
     *
     * @mbg.generated
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.classify
     *
     * @mbg.generated
     */
    private String classify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.weixin_id
     *
     * @mbg.generated
     */
    private String weixinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.photo
     *
     * @mbg.generated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.gender
     *
     * @mbg.generated
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.native_place
     *
     * @mbg.generated
     */
    private String nativePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.education
     *
     * @mbg.generated
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.idcard
     *
     * @mbg.generated
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.orgId
     *
     * @mbg.generated
     */
    private Integer orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.company
     *
     * @mbg.generated
     */
    private Integer company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.entryDate
     *
     * @mbg.generated
     */
    private String entrydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.leave
     *
     * @mbg.generated
     */
    private Integer leave;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.leaveDate
     *
     * @mbg.generated
     */
    private String leavedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.extNo
     *
     * @mbg.generated
     */
    private String extno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.wechat
     *
     * @mbg.generated
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.isManager
     *
     * @mbg.generated
     */
    private Integer ismanager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.utime
     *
     * @mbg.generated
     */
    private String utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.ctime
     *
     * @mbg.generated
     */
    private String ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.orgCode
     *
     * @mbg.generated
     */
    private String orgcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.privilege
     *
     * @mbg.generated
     */
    private String privilege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_biz_employee.goodfield
     *
     * @mbg.generated
     */
    private String goodfield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.id
     *
     * @return the value of base_biz_employee.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.id
     *
     * @param id the value for base_biz_employee.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.name
     *
     * @return the value of base_biz_employee.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.name
     *
     * @param name the value for base_biz_employee.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.eName
     *
     * @return the value of base_biz_employee.eName
     *
     * @mbg.generated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.eName
     *
     * @param ename the value for base_biz_employee.eName
     *
     * @mbg.generated
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.no
     *
     * @return the value of base_biz_employee.no
     *
     * @mbg.generated
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.no
     *
     * @param no the value for base_biz_employee.no
     *
     * @mbg.generated
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.classify
     *
     * @return the value of base_biz_employee.classify
     *
     * @mbg.generated
     */
    public String getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.classify
     *
     * @param classify the value for base_biz_employee.classify
     *
     * @mbg.generated
     */
    public void setClassify(String classify) {
        this.classify = classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.weixin_id
     *
     * @return the value of base_biz_employee.weixin_id
     *
     * @mbg.generated
     */
    public String getWeixinId() {
        return weixinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.weixin_id
     *
     * @param weixinId the value for base_biz_employee.weixin_id
     *
     * @mbg.generated
     */
    public void setWeixinId(String weixinId) {
        this.weixinId = weixinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.password
     *
     * @return the value of base_biz_employee.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.password
     *
     * @param password the value for base_biz_employee.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.photo
     *
     * @return the value of base_biz_employee.photo
     *
     * @mbg.generated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.photo
     *
     * @param photo the value for base_biz_employee.photo
     *
     * @mbg.generated
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.gender
     *
     * @return the value of base_biz_employee.gender
     *
     * @mbg.generated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.gender
     *
     * @param gender the value for base_biz_employee.gender
     *
     * @mbg.generated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.native_place
     *
     * @return the value of base_biz_employee.native_place
     *
     * @mbg.generated
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.native_place
     *
     * @param nativePlace the value for base_biz_employee.native_place
     *
     * @mbg.generated
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.education
     *
     * @return the value of base_biz_employee.education
     *
     * @mbg.generated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.education
     *
     * @param education the value for base_biz_employee.education
     *
     * @mbg.generated
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.idcard
     *
     * @return the value of base_biz_employee.idcard
     *
     * @mbg.generated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.idcard
     *
     * @param idcard the value for base_biz_employee.idcard
     *
     * @mbg.generated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.birthday
     *
     * @return the value of base_biz_employee.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.birthday
     *
     * @param birthday the value for base_biz_employee.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.orgId
     *
     * @return the value of base_biz_employee.orgId
     *
     * @mbg.generated
     */
    public Integer getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.orgId
     *
     * @param orgid the value for base_biz_employee.orgId
     *
     * @mbg.generated
     */
    public void setOrgid(Integer orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.company
     *
     * @return the value of base_biz_employee.company
     *
     * @mbg.generated
     */
    public Integer getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.company
     *
     * @param company the value for base_biz_employee.company
     *
     * @mbg.generated
     */
    public void setCompany(Integer company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.level
     *
     * @return the value of base_biz_employee.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.level
     *
     * @param level the value for base_biz_employee.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.entryDate
     *
     * @return the value of base_biz_employee.entryDate
     *
     * @mbg.generated
     */
    public String getEntrydate() {
        return entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.entryDate
     *
     * @param entrydate the value for base_biz_employee.entryDate
     *
     * @mbg.generated
     */
    public void setEntrydate(String entrydate) {
        this.entrydate = entrydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.leave
     *
     * @return the value of base_biz_employee.leave
     *
     * @mbg.generated
     */
    public Integer getLeave() {
        return leave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.leave
     *
     * @param leave the value for base_biz_employee.leave
     *
     * @mbg.generated
     */
    public void setLeave(Integer leave) {
        this.leave = leave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.leaveDate
     *
     * @return the value of base_biz_employee.leaveDate
     *
     * @mbg.generated
     */
    public String getLeavedate() {
        return leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.leaveDate
     *
     * @param leavedate the value for base_biz_employee.leaveDate
     *
     * @mbg.generated
     */
    public void setLeavedate(String leavedate) {
        this.leavedate = leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.mobile
     *
     * @return the value of base_biz_employee.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.mobile
     *
     * @param mobile the value for base_biz_employee.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.extNo
     *
     * @return the value of base_biz_employee.extNo
     *
     * @mbg.generated
     */
    public String getExtno() {
        return extno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.extNo
     *
     * @param extno the value for base_biz_employee.extNo
     *
     * @mbg.generated
     */
    public void setExtno(String extno) {
        this.extno = extno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.qq
     *
     * @return the value of base_biz_employee.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.qq
     *
     * @param qq the value for base_biz_employee.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.wechat
     *
     * @return the value of base_biz_employee.wechat
     *
     * @mbg.generated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.wechat
     *
     * @param wechat the value for base_biz_employee.wechat
     *
     * @mbg.generated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.email
     *
     * @return the value of base_biz_employee.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.email
     *
     * @param email the value for base_biz_employee.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.position
     *
     * @return the value of base_biz_employee.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.position
     *
     * @param position the value for base_biz_employee.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.isManager
     *
     * @return the value of base_biz_employee.isManager
     *
     * @mbg.generated
     */
    public Integer getIsmanager() {
        return ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.isManager
     *
     * @param ismanager the value for base_biz_employee.isManager
     *
     * @mbg.generated
     */
    public void setIsmanager(Integer ismanager) {
        this.ismanager = ismanager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.status
     *
     * @return the value of base_biz_employee.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.status
     *
     * @param status the value for base_biz_employee.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.updater
     *
     * @return the value of base_biz_employee.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.updater
     *
     * @param updater the value for base_biz_employee.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.utime
     *
     * @return the value of base_biz_employee.utime
     *
     * @mbg.generated
     */
    public String getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.utime
     *
     * @param utime the value for base_biz_employee.utime
     *
     * @mbg.generated
     */
    public void setUtime(String utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.creater
     *
     * @return the value of base_biz_employee.creater
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.creater
     *
     * @param creater the value for base_biz_employee.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.ctime
     *
     * @return the value of base_biz_employee.ctime
     *
     * @mbg.generated
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.ctime
     *
     * @param ctime the value for base_biz_employee.ctime
     *
     * @mbg.generated
     */
    public void setCtime(String ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.orgCode
     *
     * @return the value of base_biz_employee.orgCode
     *
     * @mbg.generated
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.orgCode
     *
     * @param orgcode the value for base_biz_employee.orgCode
     *
     * @mbg.generated
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.privilege
     *
     * @return the value of base_biz_employee.privilege
     *
     * @mbg.generated
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.privilege
     *
     * @param privilege the value for base_biz_employee.privilege
     *
     * @mbg.generated
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_biz_employee.goodfield
     *
     * @return the value of base_biz_employee.goodfield
     *
     * @mbg.generated
     */
    public String getGoodfield() {
        return goodfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_biz_employee.goodfield
     *
     * @param goodfield the value for base_biz_employee.goodfield
     *
     * @mbg.generated
     */
    public void setGoodfield(String goodfield) {
        this.goodfield = goodfield;
    }
}