package com.ycmm.model;

import org.springframework.data.annotation.Transient;

import java.io.Serializable;

public class BizUser implements Serializable {

    @Transient
    private String newPassword, code;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    private String id;

    private Integer type;

    private Integer manageType;

    private String name;

    private String password;

    private String gender;

    private String nickname;

    private Integer employee;

    private Integer customerId;

    private String fullname;

    private String idnumber;

    private String licenseNo;

    private String signature;

    private String secretKey;

    private String phone;

    private String phoneProvince;

    private String phoneCity;

    private Long birthday;

    private String email;

    private String qq;

    private String tel;

    private String unionId;

    private String openId;

    private String avatar;

    private String url;

    private String signin;

    private String company;

    private String companyShort;

    private String companyJob;

    private String invoice;

    private String address;

    private String referralCode;

    private Integer score;

    private Integer grade;

    private Integer utype;

    private String ucomment;

    private Integer authenStyle;

    private Integer ctype;

    private String ccomment;

    private String addrShip;

    private String addrReceive;

    private String province;

    private String city;

    private Integer source;

    private Integer userType;

    private Integer bizType;

    private String bizMain;

    private String lastLoginIp;

    private String lastLoginTime;

    private String auditComment;

    private Integer audit;

    private Integer importance;

    private Integer noticeStatus;

    private Integer transStatus;

    private Integer status;

    private String comment;

    private String updater;

    private String utime;

    private String creater;

    private String ctime;

    private Integer auditUId;

    private Integer auditCId;

    private Integer manageIdentity;

    private static final long serialVersionUID = 1L;


    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.id
     *
     * @param id the value for biz_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.type
     *
     * @return the value of biz_user.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.type
     *
     * @param type the value for biz_user.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.manage_type
     *
     * @return the value of biz_user.manage_type
     *
     * @mbg.generated
     */
    public Integer getManageType() {
        return manageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.manage_type
     *
     * @param manageType the value for biz_user.manage_type
     *
     * @mbg.generated
     */
    public void setManageType(Integer manageType) {
        this.manageType = manageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.name
     *
     * @return the value of biz_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.name
     *
     * @param name the value for biz_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.password
     *
     * @return the value of biz_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.password
     *
     * @param password the value for biz_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.gender
     *
     * @return the value of biz_user.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.gender
     *
     * @param gender the value for biz_user.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.nickname
     *
     * @return the value of biz_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.nickname
     *
     * @param nickname the value for biz_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.employee
     *
     * @return the value of biz_user.employee
     *
     * @mbg.generated
     */
    public Integer getEmployee() {
        return employee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.employee
     *
     * @param employee the value for biz_user.employee
     *
     * @mbg.generated
     */
    public void setEmployee(Integer employee) {
        this.employee = employee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.customer_id
     *
     * @return the value of biz_user.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.customer_id
     *
     * @param customerId the value for biz_user.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.fullname
     *
     * @return the value of biz_user.fullname
     *
     * @mbg.generated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.fullname
     *
     * @param fullname the value for biz_user.fullname
     *
     * @mbg.generated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.idnumber
     *
     * @return the value of biz_user.idnumber
     *
     * @mbg.generated
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.idnumber
     *
     * @param idnumber the value for biz_user.idnumber
     *
     * @mbg.generated
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.license_no
     *
     * @return the value of biz_user.license_no
     *
     * @mbg.generated
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.license_no
     *
     * @param licenseNo the value for biz_user.license_no
     *
     * @mbg.generated
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.signature
     *
     * @return the value of biz_user.signature
     *
     * @mbg.generated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.signature
     *
     * @param signature the value for biz_user.signature
     *
     * @mbg.generated
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.secret_key
     *
     * @return the value of biz_user.secret_key
     *
     * @mbg.generated
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.secret_key
     *
     * @param secretKey the value for biz_user.secret_key
     *
     * @mbg.generated
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.phone
     *
     * @return the value of biz_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.phone
     *
     * @param phone the value for biz_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.phone_province
     *
     * @return the value of biz_user.phone_province
     *
     * @mbg.generated
     */
    public String getPhoneProvince() {
        return phoneProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.phone_province
     *
     * @param phoneProvince the value for biz_user.phone_province
     *
     * @mbg.generated
     */
    public void setPhoneProvince(String phoneProvince) {
        this.phoneProvince = phoneProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.phone_city
     *
     * @return the value of biz_user.phone_city
     *
     * @mbg.generated
     */
    public String getPhoneCity() {
        return phoneCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.phone_city
     *
     * @param phoneCity the value for biz_user.phone_city
     *
     * @mbg.generated
     */
    public void setPhoneCity(String phoneCity) {
        this.phoneCity = phoneCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.birthday
     *
     * @return the value of biz_user.birthday
     *
     * @mbg.generated
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.birthday
     *
     * @param birthday the value for biz_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.email
     *
     * @return the value of biz_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.email
     *
     * @param email the value for biz_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.qq
     *
     * @return the value of biz_user.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.qq
     *
     * @param qq the value for biz_user.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.tel
     *
     * @return the value of biz_user.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.tel
     *
     * @param tel the value for biz_user.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.union_id
     *
     * @return the value of biz_user.union_id
     *
     * @mbg.generated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.union_id
     *
     * @param unionId the value for biz_user.union_id
     *
     * @mbg.generated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.open_id
     *
     * @return the value of biz_user.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.open_id
     *
     * @param openId the value for biz_user.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.avatar
     *
     * @return the value of biz_user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.avatar
     *
     * @param avatar the value for biz_user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.url
     *
     * @return the value of biz_user.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.url
     *
     * @param url the value for biz_user.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.signin
     *
     * @return the value of biz_user.signin
     *
     * @mbg.generated
     */
    public String getSignin() {
        return signin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.signin
     *
     * @param signin the value for biz_user.signin
     *
     * @mbg.generated
     */
    public void setSignin(String signin) {
        this.signin = signin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.company
     *
     * @return the value of biz_user.company
     *
     * @mbg.generated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.company
     *
     * @param company the value for biz_user.company
     *
     * @mbg.generated
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.company_short
     *
     * @return the value of biz_user.company_short
     *
     * @mbg.generated
     */
    public String getCompanyShort() {
        return companyShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.company_short
     *
     * @param companyShort the value for biz_user.company_short
     *
     * @mbg.generated
     */
    public void setCompanyShort(String companyShort) {
        this.companyShort = companyShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.company_job
     *
     * @return the value of biz_user.company_job
     *
     * @mbg.generated
     */
    public String getCompanyJob() {
        return companyJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.company_job
     *
     * @param companyJob the value for biz_user.company_job
     *
     * @mbg.generated
     */
    public void setCompanyJob(String companyJob) {
        this.companyJob = companyJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.invoice
     *
     * @return the value of biz_user.invoice
     *
     * @mbg.generated
     */
    public String getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.invoice
     *
     * @param invoice the value for biz_user.invoice
     *
     * @mbg.generated
     */
    public void setInvoice(String invoice) {
        this.invoice = invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.address
     *
     * @return the value of biz_user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.address
     *
     * @param address the value for biz_user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.referral_code
     *
     * @return the value of biz_user.referral_code
     *
     * @mbg.generated
     */
    public String getReferralCode() {
        return referralCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.referral_code
     *
     * @param referralCode the value for biz_user.referral_code
     *
     * @mbg.generated
     */
    public void setReferralCode(String referralCode) {
        this.referralCode = referralCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.score
     *
     * @return the value of biz_user.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.score
     *
     * @param score the value for biz_user.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.grade
     *
     * @return the value of biz_user.grade
     *
     * @mbg.generated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.grade
     *
     * @param grade the value for biz_user.grade
     *
     * @mbg.generated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.utype
     *
     * @return the value of biz_user.utype
     *
     * @mbg.generated
     */
    public Integer getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.utype
     *
     * @param utype the value for biz_user.utype
     *
     * @mbg.generated
     */
    public void setUtype(Integer utype) {
        this.utype = utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.ucomment
     *
     * @return the value of biz_user.ucomment
     *
     * @mbg.generated
     */
    public String getUcomment() {
        return ucomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.ucomment
     *
     * @param ucomment the value for biz_user.ucomment
     *
     * @mbg.generated
     */
    public void setUcomment(String ucomment) {
        this.ucomment = ucomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.authen_style
     *
     * @return the value of biz_user.authen_style
     *
     * @mbg.generated
     */
    public Integer getAuthenStyle() {
        return authenStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.authen_style
     *
     * @param authenStyle the value for biz_user.authen_style
     *
     * @mbg.generated
     */
    public void setAuthenStyle(Integer authenStyle) {
        this.authenStyle = authenStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.ctype
     *
     * @return the value of biz_user.ctype
     *
     * @mbg.generated
     */
    public Integer getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.ctype
     *
     * @param ctype the value for biz_user.ctype
     *
     * @mbg.generated
     */
    public void setCtype(Integer ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.ccomment
     *
     * @return the value of biz_user.ccomment
     *
     * @mbg.generated
     */
    public String getCcomment() {
        return ccomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.ccomment
     *
     * @param ccomment the value for biz_user.ccomment
     *
     * @mbg.generated
     */
    public void setCcomment(String ccomment) {
        this.ccomment = ccomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.addr_ship
     *
     * @return the value of biz_user.addr_ship
     *
     * @mbg.generated
     */
    public String getAddrShip() {
        return addrShip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.addr_ship
     *
     * @param addrShip the value for biz_user.addr_ship
     *
     * @mbg.generated
     */
    public void setAddrShip(String addrShip) {
        this.addrShip = addrShip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.addr_receive
     *
     * @return the value of biz_user.addr_receive
     *
     * @mbg.generated
     */
    public String getAddrReceive() {
        return addrReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.addr_receive
     *
     * @param addrReceive the value for biz_user.addr_receive
     *
     * @mbg.generated
     */
    public void setAddrReceive(String addrReceive) {
        this.addrReceive = addrReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.province
     *
     * @return the value of biz_user.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.province
     *
     * @param province the value for biz_user.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.city
     *
     * @return the value of biz_user.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.city
     *
     * @param city the value for biz_user.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.source
     *
     * @return the value of biz_user.source
     *
     * @mbg.generated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.source
     *
     * @param source the value for biz_user.source
     *
     * @mbg.generated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.user_type
     *
     * @return the value of biz_user.user_type
     *
     * @mbg.generated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.user_type
     *
     * @param userType the value for biz_user.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.biz_type
     *
     * @return the value of biz_user.biz_type
     *
     * @mbg.generated
     */
    public Integer getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.biz_type
     *
     * @param bizType the value for biz_user.biz_type
     *
     * @mbg.generated
     */
    public void setBizType(Integer bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.biz_main
     *
     * @return the value of biz_user.biz_main
     *
     * @mbg.generated
     */
    public String getBizMain() {
        return bizMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.biz_main
     *
     * @param bizMain the value for biz_user.biz_main
     *
     * @mbg.generated
     */
    public void setBizMain(String bizMain) {
        this.bizMain = bizMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.last_login_ip
     *
     * @return the value of biz_user.last_login_ip
     *
     * @mbg.generated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.last_login_ip
     *
     * @param lastLoginIp the value for biz_user.last_login_ip
     *
     * @mbg.generated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.last_login_time
     *
     * @return the value of biz_user.last_login_time
     *
     * @mbg.generated
     */
    public String getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.last_login_time
     *
     * @param lastLoginTime the value for biz_user.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(String lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.audit_comment
     *
     * @return the value of biz_user.audit_comment
     *
     * @mbg.generated
     */
    public String getAuditComment() {
        return auditComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.audit_comment
     *
     * @param auditComment the value for biz_user.audit_comment
     *
     * @mbg.generated
     */
    public void setAuditComment(String auditComment) {
        this.auditComment = auditComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.audit
     *
     * @return the value of biz_user.audit
     *
     * @mbg.generated
     */
    public Integer getAudit() {
        return audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.audit
     *
     * @param audit the value for biz_user.audit
     *
     * @mbg.generated
     */
    public void setAudit(Integer audit) {
        this.audit = audit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.importance
     *
     * @return the value of biz_user.importance
     *
     * @mbg.generated
     */
    public Integer getImportance() {
        return importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.importance
     *
     * @param importance the value for biz_user.importance
     *
     * @mbg.generated
     */
    public void setImportance(Integer importance) {
        this.importance = importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.notice_status
     *
     * @return the value of biz_user.notice_status
     *
     * @mbg.generated
     */
    public Integer getNoticeStatus() {
        return noticeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.notice_status
     *
     * @param noticeStatus the value for biz_user.notice_status
     *
     * @mbg.generated
     */
    public void setNoticeStatus(Integer noticeStatus) {
        this.noticeStatus = noticeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.trans_status
     *
     * @return the value of biz_user.trans_status
     *
     * @mbg.generated
     */
    public Integer getTransStatus() {
        return transStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.trans_status
     *
     * @param transStatus the value for biz_user.trans_status
     *
     * @mbg.generated
     */
    public void setTransStatus(Integer transStatus) {
        this.transStatus = transStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.status
     *
     * @return the value of biz_user.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.status
     *
     * @param status the value for biz_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.comment
     *
     * @return the value of biz_user.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.comment
     *
     * @param comment the value for biz_user.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.updater
     *
     * @return the value of biz_user.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.updater
     *
     * @param updater the value for biz_user.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.utime
     *
     * @return the value of biz_user.utime
     *
     * @mbg.generated
     */
    public String getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.utime
     *
     * @param utime the value for biz_user.utime
     *
     * @mbg.generated
     */
    public void setUtime(String utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.creater
     *
     * @return the value of biz_user.creater
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.creater
     *
     * @param creater the value for biz_user.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.ctime
     *
     * @return the value of biz_user.ctime
     *
     * @mbg.generated
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.ctime
     *
     * @param ctime the value for biz_user.ctime
     *
     * @mbg.generated
     */
    public void setCtime(String ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.audit_u_id
     *
     * @return the value of biz_user.audit_u_id
     *
     * @mbg.generated
     */
    public Integer getAuditUId() {
        return auditUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.audit_u_id
     *
     * @param auditUId the value for biz_user.audit_u_id
     *
     * @mbg.generated
     */
    public void setAuditUId(Integer auditUId) {
        this.auditUId = auditUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.audit_c_id
     *
     * @return the value of biz_user.audit_c_id
     *
     * @mbg.generated
     */
    public Integer getAuditCId() {
        return auditCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.audit_c_id
     *
     * @param auditCId the value for biz_user.audit_c_id
     *
     * @mbg.generated
     */
    public void setAuditCId(Integer auditCId) {
        this.auditCId = auditCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.manage_identity
     *
     * @return the value of biz_user.manage_identity
     *
     * @mbg.generated
     */
    public Integer getManageIdentity() {
        return manageIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.manage_identity
     *
     * @param manageIdentity the value for biz_user.manage_identity
     *
     * @mbg.generated
     */
    public void setManageIdentity(Integer manageIdentity) {
        this.manageIdentity = manageIdentity;
    }
}