package com.ycmm.business.mapper;

import com.ycmm.base.mybatis.mapper.MybatisMapper;
import com.ycmm.model.BaseBizEmployee;
import com.ycmm.model.BaseBizEmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface BaseBizEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    long countByExample(BaseBizEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    int deleteByExample(BaseBizEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    int insert(BaseBizEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    int insertSelective(BaseBizEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    List<BaseBizEmployee> selectByExample(BaseBizEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    BaseBizEmployee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BaseBizEmployee record, @Param("example") BaseBizEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BaseBizEmployee record, @Param("example") BaseBizEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseBizEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_biz_employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseBizEmployee record);
}