package com.ycmm.business.mapper;

import com.ycmm.model.BizUser;
import com.ycmm.model.BizUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BizUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    long countByExample(BizUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    int deleteByExample(BizUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    int insert(BizUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    int insertSelective(BizUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    List<BizUser> selectByExample(BizUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    BizUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BizUser record, @Param("example") BizUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BizUser record, @Param("example") BizUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BizUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BizUser record);
}